version: "3"
services:
  node:
    image: "opendigitaleducation/node:16-alpine-pnpm"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ~/.pnpm:/.pnpm
      - ../entcore-css-lib:/home/node/entcore-css-lib
      - ~/.gitconfig:/home/node/.gitconfig