node:
  image: opendigitaleducation/node:16-alpine
  working_dir: /home/node/app
  net: host
  volumes:
    - ./:/home/node/app
    - ~/.npm:/.npm
    - ../entcore-css-lib:/home/node/entcore-css-lib
    - ~/.gitconfig:/home/node/.gitconfig